/* WeddingRank UX + reputation v5.52 */
(()=>{
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const cfg=window.WEDDINGRANK_CONFIG||{},base=()=>String(cfg.SUPABASE_URL||'').replace(/\/+$/,''),key=()=>cfg.SUPABASE_ANON_KEY||cfg.SUPABASE_PUBLISHABLE_KEY||cfg.SUPABASE_KEY||'',token=()=>localStorage.getItem('wr_access_token')||'';
const hdr=(auth=false)=>({apikey:key(),Authorization:`Bearer ${auth&&token()?token():key()}`,'Content-Type':'application/json'});
async function rest(path,auth=false,opt={}){const r=await fetch(base()+'/rest/v1/'+path,{...opt,headers:{...hdr(auth),...(opt.headers||{})}}),t=await r.text();if(!r.ok)throw new Error(t||`HTTP ${r.status}`);return t?JSON.parse(t):[]}
async function uid(){if(!token())return null;try{const r=await fetch(base()+'/auth/v1/user',{headers:hdr(true)});return r.ok?(await r.json()).id:null}catch(_){return null}}
const hallId=()=>location.hash.match(/^#hall=(.+)$/)?.[1]||null;

/* compare tray safety */
const CK='wr_compare_ids',read=()=>{try{return JSON.parse(localStorage.getItem(CK)||'[]').filter(Boolean).slice(0,3)}catch(_){return[]}},write=a=>localStorage.setItem(CK,JSON.stringify([...new Set(a)].slice(0,3)));
function syncCompare(){const ids=new Set(read());document.querySelectorAll('.compareToggle').forEach(b=>{const id=b.closest('[data-id]')?.dataset.id;b.textContent=id&&ids.has(id)?'✓ 비교함':'＋ 비교'})}
function closeCompare(){const m=$('#compareModal');if(m)m.hidden=true;document.body.classList.remove('compareModalOpen');const t=$('#compareTray');if(t&&read().length)t.style.visibility=''}
function clearCompare(){write([]);syncCompare();const t=$('#compareTray');if(t){t.hidden=true;t.style.visibility='hidden'}closeCompare()}
document.addEventListener('click',e=>{if(e.target.closest?.('#clearCompare')){e.preventDefault();e.stopImmediatePropagation();clearCompare()}else if(e.target.closest?.('#compareModal .compareClose')){e.preventDefault();closeCompare()}else if(e.target?.id==='compareModal')closeCompare()},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCompare()},true);window.WeddingRankCompare={read,write,clear:clearCompare,close:closeCompare,sync:syncCompare};

function styles(){if($('#wrUxStyle'))return;const s=document.createElement('style');s.id='wrUxStyle';s.textContent=`
.reviewWrite{margin-top:34px;padding:28px;border:1px solid #ecd8d4;border-radius:20px;background:linear-gradient(180deg,#fff,#fff9f8)}.reviewWrite h3{font-size:24px;margin:0 0 8px}.reviewWrite h3:before{content:'★';margin-right:8px;color:#d59620}.scoreInputs{grid-template-columns:repeat(2,minmax(0,1fr));gap:12px!important}#reviewForm .scoreInputs>label{position:relative;margin:0!important;padding:15px;border:1px solid #eee2df;border-radius:14px;background:#fff;font-weight:800}.wrStars{display:flex;gap:3px;margin-top:8px}.wrStar{border:0;background:transparent;padding:1px;cursor:pointer;font-size:27px;color:#ddd2cf}.wrStar.on{color:#e8a318}.wrSource{position:absolute!important;width:1px!important;height:1px!important;opacity:.01!important;pointer-events:none!important}.submitReview{width:100%;min-height:54px!important;border-radius:14px!important;background:var(--rose-dark)!important;color:#fff!important;font-weight:900!important}.wrProfile{margin:14px 0 18px;padding:16px;border:1px solid #eadfdd;border-radius:16px;background:#fff}.wrProfileTop{display:flex;justify-content:space-between;gap:10px;align-items:center}.wrProfileName{font-size:17px;font-weight:900}.wrLevel{padding:6px 9px;border-radius:999px;background:#f8e8e5;color:#8b5759;font-weight:900}.wrStats{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:11px}.wrStats span{text-align:center;padding:8px 4px;border-radius:10px;background:#faf7f6;font-size:12px}.wrStats b{display:block;font-size:16px}.wrBadges{display:flex;flex-wrap:wrap;gap:5px;margin-top:9px}.wrBadge{padding:5px 8px;border:1px solid #f1dfb7;border-radius:999px;background:#fff3d9;font-size:12px}.wrNote{margin:9px 0 0;color:#786c69;font-size:12px}.wrMeta{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.wrVerified{padding:4px 7px;border-radius:999px;background:#e7f7ef;color:#19704a;font-size:11px;font-weight:900}.wrHelpful{border:1px solid #e2d7d4;background:#fff;border-radius:999px;padding:6px 10px;cursor:pointer;font-weight:800}.wrHelpful.on{background:#f8e8e5;color:#8b5759}.wrVerify{margin-top:12px;padding:13px;border:1px dashed #d9c2bd;border-radius:12px;background:#fff}.wrVerify select,.wrVerify input{width:100%;margin-top:7px}.wrVerify button{margin-top:8px;padding:10px 12px;border:0;border-radius:10px;background:#8b5759;color:#fff;font-weight:900;cursor:pointer}@media(max-width:800px){.reviewWrite{padding:20px 16px}.scoreInputs{grid-template-columns:1fr!important}.wrStats{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(s)}
function starify(){styles();const h=$('.reviewWrite h3');if(h)h.textContent='이 예식장 평가하기';const f=$('#reviewForm');if(!f)return;f.querySelectorAll('.scoreInputs label').forEach(l=>{const sel=l.querySelector('select[name]');if(!sel||sel.dataset.stars)return;sel.dataset.stars='1';sel.classList.add('wrSource');const d=document.createElement('div');d.className='wrStars';const paint=()=>d.querySelectorAll('button').forEach(x=>x.classList.toggle('on',Number(x.dataset.v)<=Number(sel.value||0)));for(let v=1;v<=5;v++){const b=document.createElement('button');b.type='button';b.className='wrStar';b.dataset.v=v;b.textContent='★';b.setAttribute('aria-label',v+'점');b.onclick=()=>{sel.value=v;paint()};d.appendChild(b)}sel.after(d);paint()})}
document.addEventListener('submit',e=>{if(!e.target.matches?.('#reviewForm'))return;if([...e.target.querySelectorAll('.scoreInputs select')].some(x=>!x.value)){e.preventDefault();e.stopImmediatePropagation();alert('8개 평가항목의 별점을 모두 선택해주세요.')}},true);

let profileBusy=false;
async function profile(){const w=$('.reviewWrite');if(!w||profileBusy)return;let box=$('#wrProfile');if(!box){box=document.createElement('div');box.id='wrProfile';w.querySelector('#authBox')?.after(box)}if(!box)return;profileBusy=true;try{const u=await uid();if(!u){box.className='wrProfile';box.innerHTML='<p class="wrNote">리뷰 +100P · 인증 +200P · 내 리뷰가 도움돼요를 받을 때마다 +5P</p>';return}const [ps,bs]=await Promise.all([rest(`profiles?select=nickname,points,level,review_count,verified_review_count,helpful_received&user_id=eq.${u}&limit=1`,true),rest(`user_badges?select=badge_code,badges(name,icon)&user_id=eq.${u}`,true)]),p=ps[0]||{nickname:'WeddingRank 회원',points:0,level:1,review_count:0,verified_review_count:0,helpful_received:0},remain=100-(Number(p.points||0)%100);box.className='wrProfile';box.innerHTML=`<div class="wrProfileTop"><span class="wrProfileName">${esc(p.nickname)}</span><span class="wrLevel">LV.${p.level} · ${Number(p.points).toLocaleString()}P</span></div><div class="wrStats"><span><b>${p.review_count}</b>리뷰</span><span><b>${p.verified_review_count}</b>인증</span><span><b>${p.helpful_received}</b>도움받음</span><span><b>${remain}</b>다음 LV까지</span></div>${bs.length?`<div class="wrBadges">${bs.map(x=>`<span class="wrBadge">${esc(x.badges?.icon||'🏅')} ${esc(x.badges?.name||x.badge_code)}</span>`).join('')}</div>`:''}<p class="wrNote">리뷰 +100P · 인증 +200P · 도움돼요 수신 +5P</p>`}catch(e){console.warn('profile',e)}finally{profileBusy=false}}
function verifyMarkup(r){if(r.verification_status==='인증완료')return '';if(r.verification_status==='인증대기')return '<div class="wrVerify">인증자료 검토 중입니다.</div>';return `<div class="wrVerify"><b>실이용 인증하면 +200P</b><select><option>견적</option><option>계약</option><option>실예식</option></select><input placeholder="인증자료 확인용 링크(선택)"><button type="button" class="wrVerifyBtn" data-id="${r.review_id}">인증 요청</button></div>`}
let reviewBusy=false,lastHall='';
async function reviews(force=false){const id=hallId(),list=$('#reviewList');if(!id||!list||reviewBusy||(!force&&lastHall===id&&list.dataset.rep==='1'))return;reviewBusy=true;try{const u=await uid(),rows=await rest(`reviews?select=review_id,user_id,visit_role,review_text,created_at,verification_status,helpful_count&hall_id=eq.${id}&order=created_at.desc&limit=20`,!!u);let mine=new Set;if(u){const vs=await rest(`review_helpful?select=review_id&user_id=eq.${u}`,true);mine=new Set(vs.map(x=>x.review_id))}list.dataset.rep='1';lastHall=id;list.innerHTML=rows.filter(r=>r.review_text).map(r=>`<article class="reviewItem"><div class="wrMeta"><b>${esc(r.visit_role||'이용자')}</b>${r.verification_status==='인증완료'?'<span class="wrVerified">✓ 인증리뷰</span>':''}<span>${esc((r.created_at||'').slice(0,10))}</span></div><p>${esc(r.review_text)}</p><button type="button" class="wrHelpful${mine.has(r.review_id)?' on':''}" data-id="${r.review_id}" ${u===r.user_id?'disabled':''}>👍 도움돼요 <span>${r.helpful_count||0}</span></button>${u===r.user_id?verifyMarkup(r):''}</article>`).join('');await profile()}catch(e){console.warn('reviews',e)}finally{reviewBusy=false}}
document.addEventListener('click',async e=>{const b=e.target.closest?.('.wrHelpful');if(b&&!b.disabled){const u=await uid();if(!u)return alert('도움돼요는 로그인 후 이용할 수 있습니다.');b.disabled=true;try{if(b.classList.contains('on'))await rest(`review_helpful?review_id=eq.${b.dataset.id}&user_id=eq.${u}`,true,{method:'DELETE',headers:{Prefer:'return=minimal'}});else await rest('review_helpful',true,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({review_id:b.dataset.id,user_id:u})});lastHall='';await reviews(true)}catch(_){alert('도움돼요 처리 중 오류가 발생했습니다.')}finally{b.disabled=false}return}const v=e.target.closest?.('.wrVerifyBtn');if(v){const u=await uid();if(!u)return alert('로그인이 필요합니다.');const box=v.closest('.wrVerify'),type=box.querySelector('select').value,evidence=box.querySelector('input').value.trim();v.disabled=true;try{await rest('review_verifications',true,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({review_id:v.dataset.id,user_id:u,verification_type:type,evidence_url:evidence||null})});box.innerHTML='인증자료 검토 중입니다.';alert('인증 요청이 접수되었습니다. 승인되면 200P가 지급됩니다.')}catch(err){alert(err.message.includes('23505')?'이미 같은 종류의 인증을 요청했습니다.':'인증 요청 처리 중 오류가 발생했습니다.')}finally{v.disabled=false}}});
let timer;const observer=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{starify();const l=$('#reviewList');if(l&&l.dataset.rep!=='1')reviews()},120)});observer.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('hashchange',()=>{lastHall='';setTimeout(()=>reviews(true),450)});styles();starify();setTimeout(()=>reviews(true),700);
})();