-- WeddingRank free board: daily editor posts plus moderated member submissions.
create table if not exists public.wedding_board_posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 2 and 120),
  body text not null check (char_length(body) between 5 and 3000),
  author_id uuid references auth.users(id) on delete set null,
  author_name text not null default 'WeddingRank' check (char_length(author_name) between 2 and 40),
  status text not null default 'pending' check (status in ('pending','published','rejected')),
  kind text not null default 'member' check (kind in ('member','daily')),
  post_date date,
  created_at timestamptz not null default now(),
  constraint wedding_board_daily_unique unique(kind,post_date),
  constraint wedding_board_member_author check (kind <> 'member' or author_id is not null)
);
create index if not exists wedding_board_visible_idx on public.wedding_board_posts(created_at desc) where status='published';
alter table public.wedding_board_posts enable row level security;
grant select on public.wedding_board_posts to anon, authenticated;
grant insert, update(status) on public.wedding_board_posts to authenticated;
grant usage, select on sequence public.wedding_board_posts_id_seq to authenticated;
-- The existing admin_users self policy protects this single-column grant.
grant select(user_id) on public.admin_users to authenticated;
create policy "Public reads approved board posts" on public.wedding_board_posts for select to anon, authenticated using (status='published');
create policy "Members read own posts" on public.wedding_board_posts for select to authenticated using (author_id=(select auth.uid()));
create policy "Board moderators read pending posts" on public.wedding_board_posts for select to authenticated using (exists(select 1 from public.admin_users a where a.user_id=(select auth.uid())));
create policy "Members submit pending posts" on public.wedding_board_posts for insert to authenticated with check (author_id=(select auth.uid()) and kind='member' and status='pending' and post_date is null and author_name<>'WeddingRank');
create policy "Administrators moderate posts" on public.wedding_board_posts for update to authenticated using (exists(select 1 from public.admin_users a where a.user_id=(select auth.uid()))) with check (exists(select 1 from public.admin_users a where a.user_id=(select auth.uid())));
