(() => {
'use strict';
const cfg=window.WEDDINGRANK_CONFIG||{},base=String(cfg.SUPABASE_URL||'').replace(/\/+$/,''),key=cfg.SUPABASE_PUBLISHABLE_KEY||cfg.SUPABASE_ANON_KEY;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token=localStorage.getItem('wr_access_token'),user=null,admin=false;
async function call(path,method='GET',data){const res=await fetch(`${base}/${path}`,{method,headers:{apikey:key,Authorization:`Bearer ${token||key}`,...(data?{'Content-Type':'application/json',Prefer:'return=minimal'}:{})},...(data?{body:JSON.stringify(data)}:{})});if(!res.ok)throw new Error(`요청 실패 (${res.status})`);return method==='GET'?res.json():null}
async function session(){if(!token||Number(localStorage.getItem('wr_expires_at')||0)<Date.now()+60000){const refresh_token=localStorage.getItem('wr_refresh_token');if(refresh_token){try{const r=await fetch(`${base}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token})}),d=await r.json();if(r.ok&&d.access_token){token=d.access_token;localStorage.setItem('wr_access_token',token);localStorage.setItem('wr_refresh_token',d.refresh_token);localStorage.setItem('wr_expires_at',String(Date.now()+d.expires_in*1000))}}catch(_){}}}
try{if(token){user=await call('auth/v1/user');const a=await call(`rest/v1/admin_users?select=user_id&user_id=eq.${encodeURIComponent(user.id)}&limit=1`);admin=a.length>0}}catch(_){user=null;admin=false}
$('#fields').hidden=!user;$('#loginNotice').innerHTML=user?`회원으로 로그인했습니다. 작성한 글은 승인 후 공개됩니다.`:'글을 쓰려면 <a href="../">메인 화면에서 로그인</a>해 주세요.'}
async function posts(){try{const rows=await call('rest/v1/wedding_board_posts?select=id,title,body,author_name,kind,status,created_at&order=created_at.desc&limit=100');const visible=rows.filter(x=>x.status==='published'||(admin&&x.status==='pending'));$('#posts').innerHTML=visible.length?visible.map(x=>`<article class="post"><div class="meta">${x.kind==='daily'?'오늘의 어른 유머':'회원 글'} · ${esc(x.author_name)} · ${esc(new Date(x.created_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'}))}${x.status==='pending'?' · 검토 대기':''}</div><h2>${esc(x.title)}</h2><div class="body">${esc(x.body)}</div>${admin&&x.status==='pending'?`<div class="moderate"><button data-id="${x.id}" data-status="published">승인</button><button data-id="${x.id}" data-status="rejected">보류</button></div>`:''}</article>`).join(''):'아직 공개된 글이 없습니다.'}catch(e){$('#posts').textContent='게시글을 불러오지 못했습니다. 잠시 뒤 다시 확인해 주세요.'}}
$('#compose').addEventListener('submit',async e=>{e.preventDefault();if(!user)return;const b=e.target.querySelector('button'),f=new FormData(e.target);b.disabled=true;$('#submitStatus').textContent='제출 중…';try{await call('rest/v1/wedding_board_posts','POST',{title:String(f.get('title')).trim(),body:String(f.get('body')).trim(),author_id:user.id,author_name:('회원 '+(user.email||'익명').split('@')[0]).slice(0,40),kind:'member',status:'pending'});e.target.reset();$('#submitStatus').textContent='접수했습니다. 관리자 검토 후 공개됩니다.'}catch(err){$('#submitStatus').textContent='등록 실패: '+err.message}finally{b.disabled=false}});
$('#posts').addEventListener('click',async e=>{const b=e.target.closest('button[data-id]');if(!b||!admin)return;b.disabled=true;try{await call(`rest/v1/wedding_board_posts?id=eq.${encodeURIComponent(b.dataset.id)}`,'PATCH',{status:b.dataset.status});await posts()}catch(err){alert('처리 실패: '+err.message);b.disabled=false}});
(async()=>{if(!base||!key){$('#posts').textContent='게시판 설정 오류';return}await session();await posts()})();
})();
