import fs from 'node:fs/promises';
import path from 'node:path';
const SUPABASE_URL='https://mozmxkmaynhxqwzovzhi.supabase.co',SUPABASE_KEY='sb_publishable_I4myPqLM3PzjLpYCPwtjrA_jfMD0prR',SITE='https://weddingrank.kr';
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`},esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),json=s=>JSON.stringify(s).replace(/</g,'\\u003c'),won=v=>v==null?'가격정보 확인중':Number(v)===0?'무료':Number(v).toLocaleString('ko-KR')+'원',slug=s=>encodeURIComponent(String(s||'').trim()).replace(/%/g,'~'),safeUrl=u=>/^https?:\/\//i.test(String(u||''))?String(u):'';
async function api(r,q){const x=await fetch(`${SUPABASE_URL}/rest/v1/${r}?${q}`,{headers});if(!x.ok)throw new Error(`${r} ${x.status} ${await x.text()}`);return x.json()}
const halls=await api('wedding_halls','select=hall_id,name,sido,sigungu,road_address,phone,website,venue_type&is_public=eq.true&operation_status=eq.%EC%9A%B4%EC%98%81&order=name.asc&limit=1000'),prices=await api('wedding_prices','select=hall_id,effective_date,rental_fee,meal_price_per_person,minimum_guarantee&order=effective_date.desc&limit=5000'),rooms=await api('hall_rooms','select=hall_id,room_name,floor,capacity_min,capacity_max&order=hall_id.asc,room_name.asc&limit=5000'),latest=new Map(),roomsByHall=new Map();for(const p of prices)if(p.hall_id&&!latest.has(p.hall_id))latest.set(p.hall_id,p);for(const r of rooms){if(!r.hall_id)continue;if(!roomsByHall.has(r.hall_id))roomsByHall.set(r.hall_id,[]);roomsByHall.get(r.hall_id).push(r)}
await fs.rm('venue',{recursive:true,force:true});await fs.mkdir('venue',{recursive:true});await fs.rm('area',{recursive:true,force:true});await fs.mkdir('area',{recursive:true});const urls=[];
const baseStyle=`body{margin:0;font-family:system-ui,-apple-system,"Noto Sans KR",sans-serif;color:#202126;background:#fff}.wrap{max-width:980px;margin:auto;padding:28px 20px 70px}.brand{text-decoration:none;color:#202126;font-size:26px;font-weight:900}.brand i{color:#ff3f78;font-style:normal}.hero{padding:48px 20px 28px;background:linear-gradient(135deg,#fff3f7,#f5f2ff);margin:20px -20px}.eyebrow{color:#d83f6e;font-weight:900}.hero h1{font-size:38px;letter-spacing:-1.5px;margin:8px 0}.hero p{color:#6f6870;line-height:1.7}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px}.card{display:block;color:#202126;text-decoration:none;border:1px solid #eee5e8;border-radius:18px;padding:18px;box-shadow:0 8px 24px rgba(60,30,45,.05)}.card:hover{border-color:#ffc5d6}.card b,.card span,.card em{display:block}.card b{font-size:18px}.card span{color:#777;margin:8px 0;font-size:13px}.card em{font-style:normal;color:#d83f6e;font-size:12px;font-weight:800}.back{display:inline-block;margin-top:28px;color:#d83f6e;text-decoration:none;font-weight:800}.crumbs{font-size:13px;color:#777;margin:18px 0}.crumbs a{color:#b33a61;text-decoration:none}.note{font-size:13px;color:#777;line-height:1.65}.official{color:#b33a61;font-weight:800;text-decoration:none}@media(max-width:600px){.hero h1{font-size:30px}}`;
for(const h of halls){
  const id=h.hall_id,p=latest.get(id),hallRooms=roomsByHall.get(id)||[],region=[h.sido,h.sigungu].filter(Boolean).join(' '),canonical=`${SITE}/venue/${id}/`,districtUrl=h.sido&&h.sigungu?`${SITE}/area/${slug(h.sido)}/${slug(h.sigungu)}/`:h.sido?`${SITE}/area/${slug(h.sido)}/`:`${SITE}/regions.html`,title=`${h.name} 예식장 가격·홀 정보 | WeddingRank`,desc=`${region} ${h.name}의 주소·전화·예식장 유형${hallRooms.length?'·홀 정보':''}${p?'·확인된 가격 정보':''}를 WeddingRank에서 확인하세요.`,official=safeUrl(h.website),peers=h.sido&&h.sigungu?halls.filter(x=>x.hall_id!==id&&x.sido===h.sido&&x.sigungu===h.sigungu).slice(0,5):[];
  const structured={'@context':'https://schema.org','@graph':[
    {'@type':'WebPage','@id':canonical+'#webpage',url:canonical,name:title,description:desc,inLanguage:'ko-KR',isPartOf:{'@type':'WebSite','@id':SITE+'/#website',url:SITE+'/',name:'WeddingRank'}},
    {'@type':'LocalBusiness','@id':canonical+'#venue',name:h.name,url:canonical,description:desc,address:{'@type':'PostalAddress',streetAddress:h.road_address||undefined,addressRegion:h.sido||undefined,addressLocality:h.sigungu||undefined,addressCountry:'KR'},telephone:h.phone||undefined,sameAs:official?[official]:undefined,additionalType:h.venue_type||undefined},
    {'@type':'BreadcrumbList',itemListElement:[
      {'@type':'ListItem',position:1,name:'WeddingRank',item:SITE+'/'},
      {'@type':'ListItem',position:2,name:h.sido||'전국 예식장',item:h.sido?`${SITE}/area/${slug(h.sido)}/`:`${SITE}/regions.html`},
      ...(h.sigungu?[{'@type':'ListItem',position:3,name:h.sigungu,item:districtUrl},{'@type':'ListItem',position:4,name:h.name,item:canonical}]:[{'@type':'ListItem',position:3,name:h.name,item:canonical}])
    ]}
  ]};
  const roomHtml=hallRooms.length?`<section class="box"><h2>웨딩홀 정보</h2>${hallRooms.map(r=>{const caps=[];if(r.capacity_min)caps.push(`최소 ${Number(r.capacity_min).toLocaleString('ko-KR')}명`);if(r.capacity_max)caps.push(`최대 ${Number(r.capacity_max).toLocaleString('ko-KR')}명`);return `<div class="row"><b>${esc(r.room_name||'홀')}</b><span>${[r.floor,...caps].filter(Boolean).map(esc).join(' · ')||'세부정보 확인중'}</span></div>`}).join('')}<p class="note">홀 구성과 수용인원은 예식장 운영 상황에 따라 변경될 수 있으므로 계약 전 최종 확인하세요.</p></section>`:`<section class="box"><h2>웨딩홀 정보</h2><p>홀 정보 확인중입니다.</p></section>`;
  const peerHtml=peers.length?`<section class="box"><h2>${esc(h.sigungu)} 다른 예식장</h2><div class="grid">${peers.map(x=>`<a class="card" href="${SITE}/venue/${x.hall_id}/"><b>${esc(x.name)}</b><span>${esc(x.road_address||region)}</span><em>비교하기 →</em></a>`).join('')}</div></section>`:'';
  const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:site_name" content="WeddingRank"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${canonical}"><script type="application/ld+json">${json(structured)}</script><style>${baseStyle}.box{border:1px solid #eee5e8;border-radius:20px;padding:22px;margin:15px 0}.row{display:grid;grid-template-columns:110px 1fr;gap:14px;padding:12px 0;border-bottom:1px solid #f0ecee}.row:last-child{border-bottom:0}.price{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.price div{background:#fff4f7;border-radius:14px;padding:14px}.cta{display:block;text-align:center;margin-top:24px;padding:15px;border-radius:13px;background:#ff3f78;color:#fff;text-decoration:none;font-weight:900}@media(max-width:600px){.price{grid-template-columns:1fr}.row{grid-template-columns:90px 1fr}}</style></head><body><main class="wrap"><a class="brand" href="/">WeddingRank <i>♥</i></a><nav class="crumbs"><a href="/">홈</a> › ${h.sido?`<a href="${SITE}/area/${slug(h.sido)}/">${esc(h.sido)}</a> › `:''}${h.sigungu?`<a href="${districtUrl}">${esc(h.sigungu)}</a> › `:''}${esc(h.name)}</nav><section class="hero"><div class="eyebrow">${esc(region)} 예식장</div><h1>${esc(h.name)}</h1><p>${esc(desc)}</p></section><section class="box"><h2>기본 정보</h2><div class="row"><b>주소</b><span>${esc(h.road_address||'주소 확인중')}</span></div><div class="row"><b>전화</b><span>${esc(h.phone||'전화번호 확인중')}</span></div><div class="row"><b>유형</b><span>${esc(h.venue_type||'예식장')}</span></div>${official?`<div class="row"><b>공식 사이트</b><span><a class="official" href="${esc(official)}" rel="nofollow noopener" target="_blank">공식 홈페이지 방문 ↗</a></span></div>`:''}</section>${roomHtml}<section class="box"><h2>가격 정보</h2>${p?`<div class="price"><div>대관료<br><b>${esc(won(p.rental_fee))}</b></div><div>1인 식대<br><b>${esc(won(p.meal_price_per_person))}</b></div><div>최소보증<br><b>${p.minimum_guarantee?Number(p.minimum_guarantee).toLocaleString('ko-KR')+'명':'확인중'}</b></div></div><p class="note">가격 기준일: ${esc(p.effective_date||'확인일 미상')} · 시기·요일·시간·프로모션에 따라 달라질 수 있으므로 계약 전 예식장에 최종 확인하세요.</p>`:'<p>가격정보 확인중입니다.</p><p class="note">확인되지 않은 가격은 임의 추정하지 않습니다.</p>'}</section>${peerHtml}<a class="cta" href="${SITE}/#hall=${encodeURIComponent(id)}">상세 비교·후기·상담 보기 →</a><a class="back" href="${districtUrl}">← ${esc(region||'지역별')} 예식장 보기</a></main></body></html>`;
  const dir=path.join('venue',id);await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'index.html'),html);urls.push(canonical)
}
const provinces=new Map(),groups=new Map();for(const h of halls){if(!h.sido)continue;if(!provinces.has(h.sido))provinces.set(h.sido,[]);provinces.get(h.sido).push(h);if(h.sigungu){const k=`${h.sido}|${h.sigungu}`;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(h)}}
for(const [sido,list] of provinces){const districts=new Map();for(const h of list){const d=h.sigungu||'기타';if(!districts.has(d))districts.set(d,[]);districts.get(d).push(h)}const canonical=`${SITE}/area/${slug(sido)}/`,title=`${sido} 예식장·웨딩홀 지역별 찾기 | WeddingRank`,desc=`${sido} 예식장·웨딩홀 ${list.length}곳을 시·군·구별로 찾아보세요.`,items=[...districts].sort((a,b)=>a[0].localeCompare(b[0],'ko')).map(([d,rows])=>d==='기타'?`<div class="card"><b>기타 지역</b><span>${rows.length}곳</span></div>`:`<a class="card" href="${SITE}/area/${slug(sido)}/${slug(d)}/"><b>${esc(d)}</b><span>예식장·웨딩홀 ${rows.length}곳</span><em>예식장 보기 →</em></a>`).join(''),structured={'@context':'https://schema.org','@graph':[{'@type':'CollectionPage',name:`${sido} 예식장·웨딩홀`,url:canonical,description:desc,mainEntity:{'@type':'ItemList',numberOfItems:districts.size,itemListElement:[...districts].filter(([d])=>d!=='기타').map(([d],i)=>({'@type':'ListItem',position:i+1,name:`${sido} ${d} 예식장`,url:`${SITE}/area/${slug(sido)}/${slug(d)}/`}))}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'WeddingRank',item:SITE+'/'},{'@type':'ListItem',position:2,name:sido,item:canonical}]}]};const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${canonical}"><script type="application/ld+json">${json(structured)}</script><style>${baseStyle}</style></head><body><main class="wrap"><a class="brand" href="/">WeddingRank <i>♥</i></a><nav class="crumbs"><a href="/">홈</a> › <a href="/regions.html">지역별 예식장</a> › ${esc(sido)}</nav><section class="hero"><div class="eyebrow">지역별 웨딩홀 찾기</div><h1>${esc(sido)} 예식장 ${list.length}곳</h1><p>${esc(desc)}</p></section><section class="grid">${items}</section><p class="note">WeddingRank는 공개·운영중으로 확인된 예식장을 기준으로 지역 페이지를 자동 갱신합니다.</p><a class="back" href="${SITE}/regions.html">← 전국 지역 선택</a></main></body></html>`;const dir=path.join('area',slug(sido));await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'index.html'),html);urls.push(canonical)}
for(const [key,list] of groups){const [sido,sigungu]=key.split('|'),canonical=`${SITE}/area/${slug(sido)}/${slug(sigungu)}/`,title=`${sigungu} 예식장·웨딩홀 추천·가격 비교 | WeddingRank`,desc=`${sido} ${sigungu} 예식장·웨딩홀 ${list.length}곳의 위치와 가격정보 확인 여부를 비교하세요.`,items=list.map(h=>`<a class="card" href="${SITE}/venue/${h.hall_id}/"><b>${esc(h.name)}</b><span>${esc(h.road_address||`${sido} ${sigungu}`)}</span><em>${latest.has(h.hall_id)?'가격정보 확인됨':'가격정보 확인중'}</em></a>`).join(''),structured={'@context':'https://schema.org','@graph':[{'@type':'CollectionPage',name:`${sido} ${sigungu} 예식장·웨딩홀`,url:canonical,description:desc,mainEntity:{'@type':'ItemList',numberOfItems:list.length,itemListElement:list.map((h,i)=>({'@type':'ListItem',position:i+1,name:h.name,url:`${SITE}/venue/${h.hall_id}/`}))}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'WeddingRank',item:SITE+'/'},{'@type':'ListItem',position:2,name:sido,item:`${SITE}/area/${slug(sido)}/`},{'@type':'ListItem',position:3,name:sigungu,item:canonical}]}]};const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${canonical}"><script type="application/ld+json">${json(structured)}</script><style>${baseStyle}</style></head><body><main class="wrap"><a class="brand" href="/">WeddingRank <i>♥</i></a><nav class="crumbs"><a href="/">홈</a> › <a href="${SITE}/area/${slug(sido)}/">${esc(sido)}</a> › ${esc(sigungu)}</nav><section class="hero"><div class="eyebrow">${esc(sido)} 지역 웨딩홀</div><h1>${esc(sigungu)} 예식장 ${list.length}곳</h1><p>${esc(desc)}</p></section><section class="grid">${items}</section><p class="note">가격이 확인되지 않은 예식장은 임의 금액 대신 ‘가격정보 확인중’으로 표시합니다.</p><a class="back" href="${SITE}/area/${slug(sido)}/">← ${esc(sido)} 지역 선택</a></main></body></html>`;const dir=path.join('area',slug(sido),slug(sigungu));await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'index.html'),html);urls.push(canonical)}
const sitemap=[`${SITE}/`,`${SITE}/regions.html`,...urls],today=new Date().toISOString().slice(0,10),xml=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${sitemap.map((u,i)=>`  <url><loc>${u}</loc><lastmod>${today}</lastmod><changefreq>${i<2?'daily':'weekly'}</changefreq><priority>${i===0?'1.0':i===1?'0.9':'0.8'}</priority></url>`).join('\n')}\n</urlset>\n`;await fs.writeFile('sitemap.xml',xml);console.log(`Generated ${halls.length} venues, ${rooms.length} rooms, ${provinces.size} province hubs, ${groups.size} district pages, ${sitemap.length} sitemap URLs.`);
